* About
This is a bash script mainly for my debian enviroment.

Installs the tools and programs I use personally.


* Usage
** Installation
Execute the following commands, it will download the script and execute the script.

*Warning*: The quick install it will add a few configuration lines to the .bashrc file. If you don't want that, use the /no-bashrc-config/ flag

Quick Install:
#+BEGIN_SRC bash
git clone --depth 1 https://github.com/zMenta/menta-install-script.git ~/menta_install_script
bash ~/menta_install_script/installScript
#+END_SRC

** Flags
Extra flags to customize the installation.

Example:
#+BEGIN_SRC bash
bash ~/menta_install_script/installScript no-latex no-revealjs
#+END_SRC

*** no-latex
You can opt to don't install latex since texlive-full can be a bit large.


*** no-doom
Don't install doom emacs.


*** no-revealjs
Don't install reveal Js and it's dependecies

Dependencies:
    + NodeJs


*** doom-default
Use default doom emacs configuration instead of my config files.
(Don't download and apply my config files)

*** no-godot
Don't create a godot engine directory on the home directory.

*** no-bashrc-config
Dont't insert configuration lines automatically to the .bashrc file depeding on the packages installed.


It will add the following lines to .bashrc file based on each package:

+ Default:
  * alias emacs="emacsclient -c -a ''"


+ Doom emacs
  * export PATH="$HOME/.emacs.d/bin:$PATH"


+ Godot
  * export PATH="$HOME/godot:$PATH"


* Software List
List of software's this script downloads.

+ ripgrep
+ vim
+ htop
+ emacs + doom emacs + my personal config files
+ brave browser
+ latex (texlive-full)
+ nodeJs and revealjs
